---
title: "analysis"
author: "Marina Melkonyan"
date: "2024-11-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(ggplot2)
library(corrplot)
library(lubridate)
library(GGally)
library(knitr)
library(ggcorrplot)
library(FactoMineR)
library(factoextra)
library(pheatmap)
```

```{r}
col_types <- c(rep("text", 4), 
               "date", 
               "date",
               rep("text", 39)) 


file_path <- "water_data.xlsx"
data <- read_excel(file_path, col_types = col_types)
```

**Data Cleaning**

```{r}
colnames(data) <- gsub(" ", "_", colnames(data))
colnames(data) <- gsub("_+", "_", colnames(data))  
colnames(data) <- gsub("_$", "", colnames(data))   # Remove trailing underscores
colnames(data) <- gsub("^_", "", colnames(data))   # Remove leading underscores
colnames(data) <- gsub(" ", "_", colnames(data))   # Replace spaces with single underscores

# Rename columns with underscores and special characters to English equivalents
colnames(data)[colnames(data) == "Դիտակետի_համար"] <- "Station_Number"
colnames(data)[colnames(data) == "Ջրային_օբյեկտ"] <- "Water_Object"
colnames(data)[colnames(data) == "Գետավազան"] <- "River_Basin"
colnames(data)[colnames(data) == "Դիտակետի_տեղադրություն"] <- "Station_Location"
colnames(data)[colnames(data) == "Ամսաթիվ"] <- "Date"
colnames(data)[colnames(data) == "Նմուշառման_ժամը"] <- "Sampling_Time"
colnames(data)[colnames(data) == "Լուծված_թթվածին._մգ/լ"] <- "Dissolved_Oxygen"
colnames(data)[colnames(data) == "ԹԿՊ5._մգ/լ"] <- "BOD5"
colnames(data)[colnames(data) == "Բիքրոմատային_օքսիդացում._մգ_Օ/լ"] <- "COD"
colnames(data)[colnames(data) == "Ամոնիում_իոն._մգ_N_/լ"] <- "NH4"
colnames(data)[colnames(data) == "Նիտրիտ_իոն._մգ_N_/լ"] <- "NO2"
colnames(data)[colnames(data) == "Նիտրատ_իոն._մգ_N_/լ"] <- "NO3"
colnames(data)[colnames(data) == "ֆոսֆատներ._մգ/լ"] <- "PO4"
colnames(data)[colnames(data) == "Zn_մգ/լ"] <- "Zn"
colnames(data)[colnames(data) == "Cu_մգ/լ"] <- "Cu"
colnames(data)[colnames(data) == "Cr_մգ/լ"] <- "Cr"
colnames(data)[colnames(data) == "As_մգ/լ"] <- "As"
colnames(data)[colnames(data) == "Cd_մգ/լ"] <- "Cd"
colnames(data)[colnames(data) == "Pb_մգ/լ"] <- "Pb"
colnames(data)[colnames(data) == "Ni_մգ/լ"] <- "Ni"
colnames(data)[colnames(data) == "Mo_մգ/լ"] <- "Mo"
colnames(data)[colnames(data) == "Mn_մգ/լ"] <- "Mn"
colnames(data)[colnames(data) == "V_մգ/լ"] <- "V"
colnames(data)[colnames(data) == "Co_մգ/լ"] <- "Co"
colnames(data)[colnames(data) == "Fe_մգ/լ"] <- "Fe"
colnames(data)[colnames(data) == "Ca_մգ/լ"] <- "Ca"
colnames(data)[colnames(data) == "Mg_մգ/լ"] <- "Mg"
colnames(data)[colnames(data) == "Ba_մգ/լ"] <- "Ba"
colnames(data)[colnames(data) == "Be_մգ/լ"] <- "Be"
colnames(data)[colnames(data) == "K_մգ/լ"] <- "K"
colnames(data)[colnames(data) == "Na_մգ/լ"] <- "Na"
colnames(data)[colnames(data) == "B_մգ/լ"] <- "B"
colnames(data)[colnames(data) == "Al_մգ/լ"] <- "Al"
colnames(data)[colnames(data) == "Se_մգ/լ"] <- "Se"
colnames(data)[colnames(data) == "Sb_մգ/լ"] <- "Sb"
colnames(data)[colnames(data) == "Sn_մգ/լ"] <- "Sn"
colnames(data)[colnames(data) == "Ընդհանուր_անօրգանական_ազոտ._մգ_N_/լ"] <- "Total_Inorganic_N"
colnames(data)[colnames(data) == "P_մգ/լ"] <- "P"
colnames(data)[colnames(data) == "Քլորիդ_իոն._մգ/լ"] <- "Cl"
colnames(data)[colnames(data) == "Սուլֆատ_իոն._մգ/լ"] <- "SO4"
colnames(data)[colnames(data) == "Սիլիցիում._մգ/լ"] <- "Si"
colnames(data)[colnames(data) == "ԸԼՆ._Հանքայնացում_._մգ/լ."] <- "TDS"
colnames(data)[colnames(data) == "Տեսակարար_էլեկտրահաղորդականություն._Միկրոսիմ./սմ2"] <- "EC_microS_cm"
colnames(data)[colnames(data) == "Կոշտություն,_մգ-էկվ/լ"] <- "Hardness"
colnames(data)[colnames(data) == "Կախված_մասնիկներ._մգ/լ"] <- "Suspended_Solids"
```

```{r}
print(colnames(data))
```

```{r}
data[ , 7:45] <- lapply(data[ , 7:45], function(x) {
  x <- gsub("<0.001", "0", x) 
  suppressWarnings(as.numeric(x))  
})

data[ , 7:45] <- lapply(data[ , 7:45], function(x) replace(x, is.na(x), 0))
```


```{r}
data$Date <- as.Date(data$Date)
data$Sampling_Time <- format(data$Sampling_Time, "%H:%M")
```

```{r}
str(data)
```

```{r}
sum(is.na(data$Date))
sum(is.na(data$Sampling_Time))
```

```{r}
data$Sampling_Time[12] <- "10:00"
data$Sampling_Time[41] <- "11:00"
data$Sampling_Time[73] <- "11:40"
data$Sampling_Time[106] <- "12:30"
data$Sampling_Time[127] <- "14:15"
data$Sampling_Time[137] <- "16:30"
data$Sampling_Time[168] <- "10:30"
data$Sampling_Time[201] <- "12:30"
data$Sampling_Time[221] <- "14:30"
data$Sampling_Time[252] <- "15:00"
data$Sampling_Time[266] <- "17:30"
data$Sampling_Time[284] <- "16:00"
data$Sampling_Time[314] <- "15:30"
data$Sampling_Time[347] <- "14:40"
data$Sampling_Time[441] <- "13:00"
data$Sampling_Time[498] <- "14:40"
data$Sampling_Time[512] <- "14:20"
data$Sampling_Time[1041] <- "10:00"
data$Sampling_Time[1073] <- "13:00"
data$Sampling_Time[1101] <- "13:30"
data$Sampling_Time[1143] <- "14:30"
data$Sampling_Time[1149] <- "12:00"
data$Sampling_Time[1174] <- "15:30"
data$Sampling_Time[1180] <- "10:30"
data$Sampling_Time[1194] <- "19:00"
data$Sampling_Time[1219] <- "16:30"
data$Sampling_Time[1225] <- "18:00"
data$Sampling_Time[1239] <- "17:00"
data$Sampling_Time[1260] <- "13:30"
data$Sampling_Time[1266] <- "16:00"
data$Sampling_Time[1280] <- "15:00"
data$Sampling_Time[1306] <- "14:00"
data$Sampling_Time[1312] <- "14:00"
data$Sampling_Time[1338] <- "14:30"
data$Sampling_Time[1344] <- "12:00"
data$Sampling_Time[1370] <- "15:00"
data$Sampling_Time[1376] <- "11:30"
data$Sampling_Time[1383] <- "09:20"
data$Sampling_Time[1409] <- "17:30"
data$Sampling_Time[1415] <- "10:30"
data$Sampling_Time[1424] <- "10:30"
data$Sampling_Time[1434] <- "11:20"
data$Sampling_Time[1452] <- "16:30"
data$Sampling_Time[1473] <- "15:30"
data$Sampling_Time[1494] <- "15:00"
data$Sampling_Time[1515] <- "12:30"
data$Sampling_Time[1538] <- "12:30"
data$Sampling_Time[1561] <- "13:30"
data$Sampling_Time[1584] <- "15:00"
data$Sampling_Time[1608] <- "15:40"
data$Sampling_Time[1631] <- "13:30"
data$Sampling_Time[1655] <- "13:00"
data$Sampling_Time[1680] <- "11:00"
data$Sampling_Time[1706] <- "11:30"
data$Sampling_Time[1720] <- "17:30"
data$Sampling_Time[1743] <- "16:30"
data$Sampling_Time[1767] <- "12:30"
data$Sampling_Time[1792] <- "14:30"
data$Sampling_Time[1816] <- "14:00"
data$Sampling_Time[1830] <- "16:00"
data$Sampling_Time[1853] <- "17:30"
data$Sampling_Time[1875] <- "12:30"
data$Sampling_Time[1897] <- "13:30"
data$Sampling_Time[1991] <- "16:00"
data$Sampling_Time[2008] <- "10:30"
data$Sampling_Time[2011] <- "12:00"
data$Sampling_Time[2109] <- "16:40"
data$Sampling_Time[2115] <- "12:00"
data$Sampling_Time[2135] <- "09:30"
data$Sampling_Time[2209] <- "11:00"
data$Sampling_Time[2237] <- "17:30"
data$Sampling_Time[2270] <- "11:00"
data$Sampling_Time[2294] <- "12:30"
data$Sampling_Time[2304] <- "10:00"
data$Sampling_Time[2306] <- "18:00"
data$Sampling_Time[2335] <- "10:10"
data$Sampling_Time[2337] <- "18:02"
data$Sampling_Time[2366] <- "10:30"
data$Sampling_Time[2368] <- "18:06"
data$Sampling_Time[2397] <- "10:40"
data$Sampling_Time[2399] <- "18:10"
data$Sampling_Time[2428] <- "10:50"
data$Sampling_Time[2430] <- "18:12"
data$Sampling_Time[2458] <- "11:00"
data$Sampling_Time[2460] <- "18:14"
data$Sampling_Time[2490] <- "10:20"
data$Sampling_Time[2492] <- "18:04"
data$Sampling_Time[2498] <- "09:00"
data$Sampling_Time[2530] <- "09:15"
data$Sampling_Time[2562] <- "09:50"
data$Sampling_Time[2595] <- "10:30"
data$Sampling_Time[2626] <- "10:30"
data$Sampling_Time[2658] <- "09:30"
data$Sampling_Time[2690] <- "07:34"
data$Sampling_Time[2722] <- "11:00"
data$Sampling_Time[2754] <- "11:15"
```

```{r}
data$Sampling_Time[is.na(data$Sampling_Time)] <- "00:00"
```

```{r}
sum(is.na(data$Sampling_Time))
```

```{r}
data <- data %>%
  filter(!is.na(Date))
```

```{r}
data$DateTime <- as.POSIXct(paste(data$Date, data$Sampling_Time), format = "%Y-%m-%d %H:%M", tz = "UTC")
```

```{r}
str(data)
```


```{r}
threshold <- 1e-10 

data_cleaned <- data

data_cleaned[, 7:45] <- lapply(data_cleaned[, 7:45], function(x) {
  if (is.numeric(x)) {
    x[abs(x) < threshold] <- 0  
  }
  return(x) 
})
```

```{r}
write.csv(data_cleaned, "cleaned_water_data.csv", row.names = FALSE)
```

**Exploratory Data Analysis (EDA)**

```{r}
# Univariate Analysis - Histogram of Dissolved Oxygen
ggplot(data_cleaned, aes(x = Dissolved_Oxygen)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  labs(title = "Distribution of Dissolved Oxygen", x = "Dissolved Oxygen (mg/L)", y = "Frequency")
```
```{r}
# Temporal Trends - Dissolved Oxygen Over Time
ggplot(data_cleaned, aes(x = Datetime, y = Dissolved_Oxygen)) +
  geom_line(color = "blue") +
  labs(title = "Dissolved Oxygen Over Time", x = "Date", y = "Dissolved Oxygen (mg/L)")
```


**Outlier Detection**

**Time Series Analysis**

```{r}
# Time Series for BOD5 and COD
ggplot(data_cleaned, aes(x = Datetime)) +
  geom_line(aes(y = BOD5, color = "BOD5")) +
  geom_line(aes(y = COD, color = "COD")) +
  labs(title = "Temporal Trends of BOD5 and COD", x = "Datetime", y = "Concentration (mg/L)") +
  scale_color_manual(values = c("BOD5" = "green", "COD" = "orange"))
```

**Correlation Analysis**

```{r}
# Select numeric columns
numeric_cols <- data_cleaned %>%
  select(where(is.numeric))

# Compute correlation matrix
cor_matrix <- cor(numeric_cols, use = "complete.obs")
pairs(numeric_cols[, 1:8], main = "Scatterplot Matrix for Selected Variables")
```

**Principal Component Analysis (PCA)**

```{r}
numeric_data <- data_cleaned %>%
  select(where(is.numeric))
```

```{r}
numeric_data <- numeric_data %>%
  select(where(~ all(!is.na(.)))) 
```

```{r}
numeric_data_scaled <- scale(numeric_data)
```

```{r}
data_pca = prcomp(x = numeric_data_scaled, center = T, scale. = T)
summary(data_pca)
```

```{r}
pheatmap(numeric_data_scaled, cluster_rows = T, cluster_cols = T)
```

```{r}
fviz_screeplot(data_pca, addlabels = T)
```

```{r}
fviz_pca_biplot(data_pca, axes = c(1, 2), geom = c("point", "text"), label = "var")
```


```{r}
fviz_pca_var(data_pca, col.var = "black") 
```

**Clustering**

```{r}
# Step 1: Prepare data for clustering
# Use scaled numeric data from the PCA section for clustering
data_for_clustering <- numeric_data_scaled


# Step 2: K-means Clustering
set.seed(123)  # For reproducibility

# Determine the optimal number of clusters using the Elbow Method
wss <- sapply(1:10, function(k) {
  kmeans(data_for_clustering, centers = k, nstart = 25)$tot.withinss
})

# Plot the Elbow Method
plot(1:10, wss, type = "b", pch = 19, frame = FALSE,
     xlab = "Number of Clusters",
     ylab = "Total Within-Cluster Sum of Squares",
     main = "Elbow Method for Optimal Clusters")

# Apply K-means clustering with an optimal number of clusters (e.g., 3)
kmeans_result <- kmeans(data_for_clustering, centers = 3, nstart = 25)

# Add cluster labels to the original data
data_cleaned$Cluster <- as.factor(kmeans_result$cluster)



```
```{r}
# Compute dissimilarity matrix
dist_matrix <- dist(data_for_clustering, method = "euclidean")

# Perform hierarchical clustering
hclust_result <- hclust(dist_matrix, method="complete")

# Plot the dendrogram
plot(hclust_result, labels = FALSE, hang = -1,
     main = "Dendrogram of Hierarchical Clustering",
     xlab = "Samples",
     ylab = "Height")

# Cut the dendrogram into clusters
hclust_clusters <- cutree(hclust_result, k = 3)

# Add hierarchical clustering labels to the original data
data_cleaned$HCluster <- as.factor(hclust_clusters)

# Visualize heatmap with hierarchical clustering
pheatmap(data_for_clustering, cluster_rows = hclust_result, cluster_cols = FALSE,
         main = "Heatmap with Hierarchical Clustering")
```




**Geospatial Analysis**


```{r}
# Filter data for "Sevan Lake" and "Debed river basin"
filtered_data <- data_cleaned %>%
  filter(River_Basin %in% c("Sevan Lake", "Debed river basin", "Metsamor river basin"))

# Create a visually appealing boxplot
ggplot(filtered_data, aes(x = River_Basin, y = Dissolved_Oxygen, fill = River_Basin)) +
  geom_boxplot(outlier.color = "red", outlier.size = 2) + # Highlight outliers
  labs(
    title = "Dissolved Oxygen by River Basin",
    subtitle = "Comparing Sevan Lake and Debed River Basin",
    x = "River Basin",
    y = "Dissolved Oxygen (mg/L)"
  ) +
  scale_fill_manual(values = c("Sevan Lake" = "#1f77b4", "Debed river basin" = "#ff7f0e", "Metsamor river basin"='green')) + # Custom colors
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    legend.position = "none" # Hide legend as it's clear from labels
  )


```


